application: confweb
version: 1
runtime: python27
threadsafe: yes
api_version: 1

handlers:
- url: .*
  script: app.app

libraries:
- name: jinja2
  version: latest

env_variables:
  CACHE_BACKEND: 'Memcached'